### ISSUE TITLE
Improvements: Fixed menu bar during scrolling

### ISSUE THREAD

**Issue by bachbach** [magdalena-dering/Business-Website-Example#8]
As mentioned above, please make menu bar with fixed position. When menu will be all the time on top, we can remove 'Go to top' button, which appears when scrolling.

**Comment by magdalena-dering** [comment]
Menu bar is made as fixed position. Additionally, as we talked, I restored button when screen size is less than 767px, what is giving better functionality for web user. 
Thank you.
